#!/usr/bin/env bash
# Build the executable with SwiftPM and wrap it in a .app bundle.
#
# Output: build/DshDesktop.app
# Run:    ./scripts/bundle.sh   # then open build/DshDesktop.app

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> swift build -c release"
swift build -c release

BIN_PATH="$(swift build -c release --show-bin-path)"
EXEC="$BIN_PATH/DshDesktop"
test -x "$EXEC" || { echo "expected executable at $EXEC"; exit 1; }

APP="$ROOT/build/DshDesktop.app"
CONTENTS="$APP/Contents"
MACOS="$CONTENTS/MacOS"
RES="$CONTENTS/Resources"

echo "==> constructing $APP"
rm -rf "$APP"
mkdir -p "$MACOS" "$RES"
cp "$EXEC" "$MACOS/DshDesktop"

cat > "$CONTENTS/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>ai.deepseek.dsh.desktop</string>
    <key>CFBundleName</key>
    <string>DshDesktop</string>
    <key>CFBundleDisplayName</key>
    <string>DshDesktop</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleExecutable</key>
    <string>DshDesktop</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIconName</key>
    <string>AppIcon</string>
    <key>NSHumanReadableCopyright</key>
    <string>© 2026 DshDesktop contributors. Released under the MIT License.</string>
    <key>LSMinimumSystemVersion</key>
    <string>25.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# Bundle the icon assets (generated by scripts/build-icons.sh or committed manually)
ICON_SRC="$ROOT/Sources/DshDesktop/Resources"
test -f "$ICON_SRC/AppIcon.icns" || { echo "missing $ICON_SRC/AppIcon.icns — run scripts/build-icons.sh"; exit 1; }
cp "$ICON_SRC/AppIcon.icns" "$RES/AppIcon.icns"
test -f "$ICON_SRC/MenuBarIconTemplate.png" && cp "$ICON_SRC/MenuBarIconTemplate.png" "$RES/MenuBarIconTemplate.png"
test -f "$ICON_SRC/MenuBarIconTemplate@2x.png" && cp "$ICON_SRC/MenuBarIconTemplate@2x.png" "$RES/MenuBarIconTemplate@2x.png"

# Bundle localizations (.lproj/Localizable.strings per language)
for lproj in "$ICON_SRC"/*.lproj; do
    [ -d "$lproj" ] || continue
    cp -R "$lproj" "$RES/"
done

# Bundle the bundled dsh plugin(s). The wrapper generates a runtime
# cordis.yml that points to these, then launches dsh with `--patch`.
#
# Lookup order (first match wins):
#   1. $DSHDESKTOP_PLUGINS_DIR (env override)
#   2. ../plugins  (sibling directory of dsh-desktop, e.g. /CodeSource/plugins)
#   3. ./dsh-plugins (legacy in-repo fallback for standalone use)
#   4. none — wrapper still works, just without the bg-throttle plugin
PLUGIN_SRC=""
DSHDESKTOP_PLUGINS_DIR="${DSHDESKTOP_PLUGINS_DIR:-}"
if [ -n "$DSHDESKTOP_PLUGINS_DIR" ] && [ -d "$DSHDESKTOP_PLUGINS_DIR" ]; then
    PLUGIN_SRC="$DSHDESKTOP_PLUGINS_DIR"
elif [ -d "$ROOT/../plugins" ]; then
    PLUGIN_SRC="$ROOT/../plugins"
elif [ -d "$ROOT/dsh-plugins" ]; then
    PLUGIN_SRC="$ROOT/dsh-plugins"
fi
if [ -n "$PLUGIN_SRC" ] && [ -d "$PLUGIN_SRC" ]; then
    # We bundle ONLY the background-throttle plugin, not the user's
    # other plugins in the parent directory. The wrapper's job is to
    # ship ONE specific plugin that solves the CPU issue we know about;
    # the user's other plugins should be managed via the dsh install
    # process or their own cordis config, not pulled in by the wrapper.
    if [ -d "$PLUGIN_SRC/background-throttle" ]; then
        mkdir -p "$RES/dsh-plugins"
        cp -R "$PLUGIN_SRC/background-throttle" "$RES/dsh-plugins/background-throttle"
        echo "==> bundled dsh plugin from: $PLUGIN_SRC/background-throttle"
        find "$RES/dsh-plugins/background-throttle" -name "*.ts" -o -name "*.yml" | sed "s|$RES/||" | sort
    else
        echo "==> $PLUGIN_SRC/background-throttle not found; running dsh without bg-throttle"
    fi
else
    echo "==> no dsh plugins found (DSHDESKTOP_PLUGINS_DIR / ../plugins / dsh-plugins); running dsh without bg-throttle"
fi

echo "==> wrote $APP"
echo "next: ./scripts/sign.sh"
